### PR TITLE
Fixed deployment error on heroku at requirements.txt

### PR DESCRIPTION
**Pull request by snowfluke**
added open-cv-headless

### CODE REVIEW

**Comment by boidushya** [comment]
Good suggestion but i think it'd be better to add this under another requirements.txt specifically for people using this script on headless environment, opencv is already a pretty big package by itself, i dont think everyone would want another 35 mb for the headless one....
Alternatively you can edit the README to include an optional step for installing this for headless users...

**Comment by snowfluke** [comment]
What about replacing open-cv with open-cv-headless ?

**Comment by boidushya** [comment]
Thats actually a good idea but you have to test it once to check if it works that way...

**Comment by snowfluke** [comment]
Well, then I will try it tomorrow, I will DM your Discord

**Comment by boidushya** [comment]
Sure thing mate!
Hmu on semolini#2344

**Pull request closed without merging**
